/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    implementation(libs.lsp4j)
    testImplementation(libs.slf4j.api)
    testImplementation(libs.slf4j.simple)
}
