/*
 * This source file was generated by the Gradle 'init' task
 */
package org.xtclang.lsp.server;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
