/*
 * This source file was generated by the Gradle 'init' task
 */
package org.xtclang.lsp.server;

import org.xtclang.lsp.client.XtcLanguageClient;

import static org.xtclang.utilities.StringUtils.join;
import static org.xtclang.utilities.StringUtils.split;

import org.apache.commons.text.WordUtils;

public class XtcLanguageServer {
    public static void main(String[] args) {
        XtcLanguageClient tokens;
        tokens = split(MessageUtils.getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
