#
# This should be a complete XTC grammar en EBNF form. It should successfully validate any XTC code given.
# TODO: There should be unit tests for this on the existing XTC corpus.
#

Letter
    "A".."Z"
    "a".."z"

Digit
    "0".."9"

Digits
    Digit
    Digits Digit

DigitsNoUnderscores
    Digits

Whitespace
    "\t"
    "\n"
    "\x0b"
    "\x0c"
    "\r"
    "\x1c"
    "\x1d"
    "\x1e"
    "\x1f"
    " "
    "\x85"
    "\xa0"
    "\u1680"
    "\u2000"
    "\u2001"
    "\u2002"
    "\u2003"
    "\u2004"
    "\u2005"
    "\u2006"
    "\u2007"
    "\u2008"
    "\u2009"
    "\u200a"
    "\u2028"
    "\u2029"
    "\u202f"
    "\u205f"
    "\u3000"

LineTerminator
    "\u000a"
    "\u000b"
    "\u000c"
    "\u000d" ["\u000a"]
    "\u0085"
    "\u2028"
    "\u2029"

Name
    (<Letter> | "_") (<Letter> | <Digit> | "_")*

QualifiedName
    Name
    QualifiedName "." Name

Modifiers
    Modifier
    Modifiers Modifier

Modifier
    "static"
    AccessModifier
    Annotation

AccessModifier
    "public"
    "protected"
    "private"

Annotations
    Annotation
    Annotations Annotation

Annotation
    "@" NoWhitespace NamedTypeExpression NoWhitespace [ArgumentList]

ParameterList
    "(" Parameters ")"

Parameters
    Parameter
    Parameters "," Parameter

Parameter
    TypeExpression Name [DefaultValue]

DefaultValue
    "=" Expression

ArgumentList
    "(" [Arguments] ")"

Arguments
    Argument
    Arguments "," Argument

Argument
    [NamedArgument] ArgumentExpression

ArgumentExpression
    "_"
    "<" ExtendedTypeExpression ">" "_"
    Expression

NamedArgument
    Name "="

TypeParameterList
    "<" TypeParameters ">"

TypeParameters
    TypeParameter
    TypeParameters "," TypeParameter

TypeParameter
    Name [TypeParameterConstraint]

TypeParameterConstraint
    "extends" ExtendedTypeExpression

TypeParameterTypeList
    "<" TypeExpressionList ">"

TypeExpressionList
    TypeExpressionListElement
    TypeExpressionList "," TypeExpressionListElement

TypeExpressionListElement
    TypeParameterTypeList
    ExtendedTypeExpression

CompilationUnit
	[ImportStatements] TypeCompositionStatement

ImportStatements
	ImportStatement
	ImportStatements ImportStatement

TypeCompositionStatement
    [Modifiers] Category QualifiedName [TypeParameterList] [ParameterList] [Compositions] TypeCompositionBody

Category
    "module"
    "package"
    "class"
    "interface"
    "service"
    "const"
    "enum"
    "mixin"

Compositions
    ConditionalComposition
    Compositions ConditionalComposition

ConditionalComposition
    IfComposition
    Composition

IfComposition
    "if" "(" Expression ")" "{" Compositions "}" [ElseComposition]

ElseComposition
    "else" IfComposition
    "else" "{" Compositions "}"

Composition
    "extends" ExtendsList
    "implements" ImplementsList
    "delegates" DelegatesList
    "incorporates" IncorporatesList
    "into" AnyTypeExpression
    "import" [ImportModifier] QualifiedName [VersionRequirement] [ResourceProvider]
    "default" "(" Expression ")"

ExtendsList
    ExtendsSingle
    ExtendsList "," ExtendsSingle

ExtendsSingle
    TypeExpression [ArgumentList]

ImplementsList
    ImplementsSingle
    ImplementsList "," ImplementsSingle

ImplementsSingle
    ExtendedTypeExpression

DelegatesList
    DelegatesSingle
    DelegatesList "," DelegatesSingle

DelegatesSingle
    AnyTypeExpression "(" Expression ")"

IncorporatesList
    IncorporatesSingle
    IncorporatesList "," IncorporatesSingle

IncorporatesSingle
    "conditional" QualifiedName TypeParameterList [ArgumentList]
    TypeExpression [ArgumentList]

ImportModifier
    "embedded"
    "required"
    "desired"
    "optional"

VersionRequirement
    Version [VersionOverrides]

VersionOverrides
    VersionOverride
    VersionOverrides "," VersionOverride

VersionOverride
    VersionOverrideVerb Versions

VersionOverrideVerb
    "allow"
    "avoid"
    "prefer"

Versions
    Version
    Versions "," Version

Version
    VersionLiteral

ResourceProvider
    [ResourceList] "using" NamedTypeExpression

ResourceList
    "inject" "(" [ResourceListContents] ")"

ResourceListContents
    Resources [","]

Resources
    Resource
    Resources "," Resource

Resource
    TypeExpression ResourceFinish

ResourceFinish
    Name
    "_"

TypeCompositionBody
    "{" EnumBody "}"
    "{" TypeCompositionComponents "}"
    ";"

EnumBody
    Enums [EnumBodyFinish]

Enums
    Enum
    Enums "," Enum

EnumBodyFinish
    ";" TypeCompositionComponents

Enum
    [Annotations] Name [TypeParameterTypeList] [ArgumentList] [TypeCompositionBody]

TypeCompositionComponents
    ConditionalTypeCompositionComponent
    TypeCompositionComponents ConditionalTypeCompositionComponent

ConditionalTypeCompositionComponent
    IfTypeCompositionComponent
    TypeCompositionComponent

IfTypeCompositionComponent
    "if" "(" Expression ")" "{" TypeCompositionComponents "}" [ElseTypeCompositionComponent]

ElseTypeCompositionComponent
    "else" IfTypeCompositionComponent
    "else" "{" TypeCompositionComponents "}"

TypeCompositionComponent
    [AccessModifier] TypeDefStatement
    ImportStatement
    TypeCompositionStatement
    PropertyDeclarationStatement
    MethodDeclarationStatement

PropertyDeclarationStatement
    [PropertyModifiers] TypeExpression Name PropertyDeclarationFinish

PropertyModifiers
    PropertyModifier
    PropertyModifiers PropertyModifiers

PropertyModifier
    "static"
    PropertyAccessModifier
    Annotation

PropertyAccessModifier
    AccessModifier
    AccessModifier "/" AccessModifier

PropertyDeclarationFinish
    ";"
    PropertyDeclarationInitialValue
    "." Name Parameters MethodBody [PropertyDeclarationInitialValue]
    TypeCompositionBody [PropertyDeclarationInitialValue]

PropertyDeclarationInitialValue
    "=" Expression ";"

MethodDeclarationStatement
    [MethodModifiers] [TypeParameterList] MethodIdentity ParameterList MethodDeclarationFinish

MethodModifiers
    MethodModifier
    MethodModifiers MethodModifier

MethodModifier
    Modifier
    Annotation

MethodIdentity
    "construct"
    ["conditional"] ReturnList Name [RedundantReturnSpecifier]

ReturnList
    "void"
    SingleReturnList
    "(" MultiReturnList ")"

SingleReturnList
    TypeExpression

MultiReturnList
    MultiReturn
    MultiReturnList "," MultiReturn

MultiReturn
    TypeExpression [Name]

RedundantReturnSpecifier
    "<" TypeExpressionList ">"

MethodDeclarationFinish
    ";"
    "=" Expression ";"
    StatementBlock

Statement
    TypeCompositionStatement
    PropertyDeclarationStatement
    MethodDeclarationStatement
	VariableDeclaration ";"
	Assignment ";"
    LabeledStatement
    AssertStatement
    BreakStatement
    ContinueStatement
    DoStatement
    ForStatement
    IfStatement
	ImportStatement
	ReturnStatement
    SwitchStatement
    TryStatement
	TypeDefStatement
    UsingStatement
    WhileStatement
    StatementBlock
	Expression ";"

StatementBlock
    "{" Statements "}"

Statements
    Statement
    Statements Statement

VariableDeclaration
    VariableTypeExpression Name [VariableInitializerFinish]
    "(" OptionalDeclarationList "," OptionalDeclaration ")" "=" Expression

VariableInitializerFinish
    "=" Expression

OptionalDeclarationList
    OptionalDeclaration
    OptionalDeclarationList "," OptionalDeclaration

OptionalDeclaration
    Assignable
    VariableTypeExpression Name

VariableTypeExpression
    "val"
    "var"
    TypeExpression

Assignment
    Assignee AssignmentOperator Expression

Assignee
    Assignable
    "(" AssignableList "," Assignable ")"

AssignableList
    Assignable
    AssignableList "," Assignable

Assignable
    Name
    TernaryExpression "." Name
    TernaryExpression ArrayIndexes

AssignmentOperator
    "="
    "*="
    "/="
    "%="
    "+="
    "-="
    "<<="
    ">>="
    ">>>="
    "&="
    "&&="
    "|="
    "||="
    "^="
    "?:="
    ":="
    "?="

LabeledStatement
    Name ":" Whitespace Statement

AssertStatement
    AssertInstruction [ConditionList] [AssertMessage] ";"

AssertInstruction
    "assert"
    "assert:arg"
    "assert:bounds"
    "assert:TODO"
    "assert:once"
    "assert:rnd(" Expression ")"
    "assert:test"
    "assert:debug"

AssertMessage
    "as" Expression

ForStatement
    "for" "(" ForCondition ")" StatementBlock

ForCondition
    [VariableInitializationList] ";" [ConditionList] ";" [VariableModificationList]
    OptionalDeclaration ":" Expression
    "(" OptionalDeclarationList "," OptionalDeclaration ")" ":" Expression

VariableInitializationList
    VariableInitializer
    VariableInitializationList "," VariableInitializer

VariableInitializer
    OptionalDeclaration "=" Expression
    "(" OptionalDeclarationList "," OptionalDeclaration ")" "=" Expression

VariableModificationList
    VariableModification
    VariableModificationList "," VariableModification

VariableModification
    Assignment
    Expression

IfStatement
    "if" "(" ConditionList ")" StatementBlock [ElseStatement]

ElseStatement
    "else" IfStatement
    "else" StatementBlock

DoStatement
    "do" StatementBlock "while" "(" ConditionList ")" ";"

WhileStatement
    "while" "(" ConditionList ")" StatementBlock

ConditionList
    Condition
    ConditionList "," Condition

Condition
    ConditionalAssignmentCondition
    "!" "(" ConditionalAssignmentCondition ")"
    Expression

ConditionalAssignmentCondition
    OptionalDeclaration ConditionalAssignmentOp Expression
    "(" OptionalDeclarationList "," OptionalDeclaration ")" ConditionalAssignmentOp Expression

ConditionalAssignmentOp
    ":="
    "?="

ImportStatement
    "import" QualifiedName ImportFinish

ImportFinish
    ";"
    "as" Name ";"
    NoWhitespace ".*" ";"

ReturnStatement
    "return" [ReturnValue] ";"

ReturnValue
    TupleLiteral
    ExpressionList

SwitchStatement
    "switch" "(" SwitchCondition ")" "{" SwitchBlocks "}"

SwitchCondition
    SwitchConditionExpression
    SwitchCondition "," SwitchConditionExpression

SwitchConditionExpression
    VariableInitializer
    Expression

SwitchBlocks
    SwitchBlock
    SwitchBlocks SwitchBlock

SwitchBlock
    SwitchLabels Statements [SwitchBlockFinish]

SwitchLabels
    SwitchLabel
    SwitchLabels SwitchLabel

SwitchLabel
    "case" CaseOptionList ":"
    "default" ":"

SwitchBlockFinish
    BreakStatement
    ContinueStatement

BreakStatement
    "break" [Name] ";"

ContinueStatement
    "continue" [Name] ";"

CaseOptionList
    CaseOption
    CaseOptionList "," CaseOption

CaseOption
    "(" CaseExpressionList "," CaseExpression ")"
    SafeCaseExpression

CaseExpressionList
    CaseExpression
    CaseExpressionList "," CaseExpression

CaseExpression
    "_"
    Expression

SafeCaseExpression
    "_"
    TernaryExpression

TryStatement
    "try" [TryResources] StatementBlock TryFinish

TryResources
    "(" VariableInitializationList ")"

TryFinish
    Catches
    [Catches] "finally" StatementBlock

Catches
    Catch
    Catches Catch

Catch
    "catch" "(" TypeExpression Name ")" StatementBlock

UsingResources
    UsingResource
    UsingResources "," UsingResource

UsingResource
    OptionalDeclaration "=" Expression
    "(" OptionalDeclarationList "," OptionalDeclaration ")" "=" Expression
    Expression

UsingStatement
    "using" "(" UsingResources ")" StatementBlock

TypeDefStatement
    "typedef" AnyTypeExpression "as" Name ";"

Expression
    ElseExpression

ElseExpression
    TernaryExpression
    TernaryExpression ":" ElseExpression

TernaryExpression
    OrExpression
    OrExpression Whitespace "?" TernaryExpression ":" TernaryExpression

OrExpression
    AndExpression
    OrExpression "||" AndExpression
    OrExpression "^^" AndExpression

AndExpression
    EqualityExpression
    AndExpression "&&" EqualityExpression

EqualityExpression
    RelationalExpression
    EqualityExpression "==" RelationalExpression
    EqualityExpression "!=" RelationalExpression

RelationalExpression
    AssignmentExpression
    AssignmentExpression "<=>" AssignmentExpression
    RelationalExpression "<"   AssignmentExpression
    RelationalExpression "<="  AssignmentExpression
    RelationalExpression ">"   AssignmentExpression
    RelationalExpression ">="  AssignmentExpression

AssignmentExpression
    RangeExpression
    RangeExpression "<-" AssignmentExpression

RangeExpression
    BitwiseExpression
    RangeExpression ".." BitwiseExpression

BitwiseExpression
    AdditiveExpression
    BitwiseExpression "<<"  AdditiveExpression
    BitwiseExpression ">>"  AdditiveExpression
    BitwiseExpression ">>>" AdditiveExpression
    BitwiseExpression "&"   AdditiveExpression
    BitwiseExpression "^"   AdditiveExpression
    BitwiseExpression "|"   AdditiveExpression

AdditiveExpression
    MultiplicativeExpression
    AdditiveExpression "+" MultiplicativeExpression
    AdditiveExpression "-" MultiplicativeExpression

MultiplicativeExpression
    ElvisExpression
    MultiplicativeExpression "*"  ElvisExpression
    MultiplicativeExpression "/"  ElvisExpression
    MultiplicativeExpression "%"  ElvisExpression
    MultiplicativeExpression "/%" ElvisExpression

ElvisExpression
    PrefixExpression
    PrefixExpression "?:" ElvisExpression

PrefixExpression
    PostfixExpression
    "++" PrefixExpression
    "--" PrefixExpression
    "+" PrefixExpression
    "-" PrefixExpression
    "!" PrefixExpression
    "~" PrefixExpression

PostfixExpression
    PrimaryExpression
    PostfixExpression "++"
    PostfixExpression "--"
    PostfixExpression "(" [Arguments] ")"
    PostfixExpression ArrayDims
    PostfixExpression ArrayIndexes
    PostfixExpression NoWhitespace "?"
    PostfixExpression "." ["&"] DotNameFinish
    PostfixExpression ".new" NewFinish
    PostfixExpression ".as" "(" AnyTypeExpression ")"
    PostfixExpression ".is" "(" AnyTypeExpression ")"

ArrayDims
    "[" [DimIndicators] "]"

DimIndicators
    DimIndicator
    DimIndicators "," DimIndicator

DimIndicator
    "?"

ArrayIndexes
    "[" ExpressionList "]"

ExpressionList
    Expression
    ExpressionList "," Expression

DotNameFinish
    Name [TypeParameterTypeList]
    "default"

NewFinish
    TypeExpression NewArguments [AnonClassBody]
    ArgumentList

NewArguments
    ArrayIndexes [ArgumentList]
    ArgumentList

PrimaryExpression
    "(" Expression ")"
    "new" NewFinish
    ["&"] ["construct"] QualifiedName [TypeParameterTypeList]
    StatementExpression
    SwitchExpression
    LambdaExpression
    "_"
    Literal

AnonClassBody
    "{" TypeCompositionComponents "}"

StatementExpression
    StatementBlock
    "throw" TernaryExpression
    "TODO" [TodoFinish]
    "assert"

SwitchExpression
    "switch" "(" [SwitchCondition] ")" "{" SwitchExpressionBlocks "}"

SwitchExpressionBlocks
    SwitchExpressionBlock
    SwitchExpressionBlocks SwitchExpressionBlock

SwitchExpressionBlock
    SwitchLabels ExpressionList ";"

LambdaExpression
    LambdaInputs "->" LambdaBody

LambdaInputs
    LambdaParameterName
    LambdaInferredList
    LambdaParameterList

LambdaInferredList
    "(" LambdaParameterNames ")"

LambdaParameterNames
    LambdaParameterName
    LambdaParameterNames "," LambdaParameterName

LambdaParameterList
    "(" LambdaParameters ")"

LambdaParameters
    LambdaParameter
    LambdaParameters "," LambdaParameter

LambdaParameter
    TypeExpression LambdaParameterName

LambdaParameterName
    "_"
    Name

LambdaBody
    Expression
    StatementBlock

InputCharacter
    RawCharacter except LineTerminator

InputCharacters
    InputCharacter
    InputCharacters InputCharacter

RawCharacters
    RawCharacter
    RawCharacters RawCharacter

# TODO Any legal unicode code point except BeginningOfFile or EndOfFile
RawCharacter
    NoWhitespace
    Whitespace

TodoFinish
    (InputCharacter except "(") InputCharacters LineTerminator
    NoWhitespace "(" [Expression] ")"

Literal
    TypedNumericLiteral
    IntegerLiteral
    FPDecimalLiteral
    FPBinaryLiteral
    CharLiteral
    StringLiteral
    BinaryLiteral
    TupleLiteral
    ListLiteral
    MapLiteral
    VersionLiteral
    DateLiteral
    TimeOfDayLiteral
    TimeLiteral
    TimeZoneLiteral
    DurationLiteral
    PathLiteral
    FileLiteral
    DirectoryLiteral
    FileStoreLiteral

CharLiteral
    "'" SingleCharacter "'"

SingleCharacter
    InputCharacter except \ or '
    CharacterEscape

# TODO: Do these need extra escape backslashes?
CharacterEscape
    "\\"
    "\"
    "\b"
    "\f"
    "\n"
    "\r"
    "\t"

TypedNumericLiteral
    IntTypeName ":" IntegerLiteral
    FPTypeName ":" FPLiteral

FPLiteral
    IntegerLiteral
    FPDecimalLiteral
    FPBinaryLiteral

IntTypeName
    "Int"
    "Int8"
    "Int16"
    "Int32"
    "Int64"
    "Int128"
    "IntN"
    "Byte"
    "UInt"
    "UInt8"
    "UInt16"
    "UInt32"
    "UInt64"
    "UInt128"
    "UIntN"

FPTypeName
    "Dec"
    "Dec32"
    "Dec64"
    "Dec128"
    "DecN"
    "Float8e4"
    "Float8e5"
    "BFloat16"
    "Float16"
    "Float32"
    "Float64"
    "Float128"
    "FloatN"

StringLiteral
    '"' [CharacterString] '"'
    '$"' [CharacterString] '"'
    "\|" FreeformLiteral
    "$|" FreeformLiteral
    "$" NoWhitespace File

CharacterString
    StringCharacter
    CharacterString StringCharacter

StringCharacter
    InputCharacter except \ or "
    CharacterEscape

FreeformLiteral
    FreeformChars LineTerminator [FreeformLines]

FreeformLines
    FreeformLine
    FreeformLines FreeformLine

FreeformLine
    [Whitespace] "|" FreeformChars LineTerminator

FreeformChars
    FreeformChar
    FreeformChars FreeformChar

FreeformChar
    InputCharacter except LineTerminator

BinaryLiteral
    "#" NoWhitespace Hexits
    "#|" FreeformLiteral
    "#" NoWhitespace File

TupleLiteral
    "(" ExpressionList "," Expression ")"
    TypeExpression NoWhitespace ":" "(" [ExpressionList] ")"

CollectionLiteral
    "[" [ExpressionList] "]"
    TypeExpression NoWhitespace ":" "[" [ExpressionList] "]"

MapLiteral
    "[" [Entries] "]"
    TypeExpression NoWhitespace ":" "[" [Entries] "]"

# TODO: ExpressionList should probably also be OK as empty
ListLiteral
    "[" "]"
    "[" [ExpressionList] "]"
    TypeExpression NoWhitespace ":" "[" [ExpressionList] "]"

Entries
    Entry
    Entries "," Entry

Entry
    Expression "=" Expression

VersionLiteral
    "Version:" NoWhitespace VersionString
    "v:" NoWhitespace VersionString

VersionString
    NonGASuffix
    VersionNumbers NoWhitespace [VersionFinish] NoWhitespace [Build]

VersionNumbers
    DigitsNoUnderscores
    VersionNumbers NoWhitespace "." NoWhitespace DigitsNoUnderscores

VersionFinish
     "-" NoWhitespace NonGASuffix
     "." NoWhitespace NonGASuffix
     NonGASuffix

NonGASuffix
      NonGAPrefix NoWhitespace [NonGAVersion]

NonGAVersion
    "-" NoWhitespace DigitsNoUnderscores
    "." NoWhitespace DigitsNoUnderscores
    DigitsNoUnderscores

Build
    "+" NoWhitespace BuildChars

BuildChars
    BuildChar
    BuildChars BuildChar

BuildChar
    "0".."9"
    "A".."Z"
    "a".."z"
    "-"
    "."

NonGAPrefix
    "dev"
    "ci"
    "qc"
    "alpha"
    "beta"
    "rc"

DateLiteral
    "Date:" Digit Digit Digit Digit "-" Digit Digit "-" Digit Digit

TimeOfDayLiteral
    "TimeOfDay:" Digit Digit ":" Digit Digit [Seconds]

Seconds
     ":" Digit Digit [SecondsFraction]

SecondsFraction
     "." NoWhitespace Digits

TimeLiteral
    "Time:" Digit Digit Digit Digit "-" Digit Digit "-" Digit Digit "T" Digit Digit ":" Digit Digit [Seconds] [TimeZone]

TimeZoneLiteral
    "TimeZone:" NoWhitespace TimeZone

TimeZone
    "Z"
    "+" NoWhitespace Digit NoWhitespace Digit NoWhitespace [MinutesOffset]
    "-" NoWhitespace Digit NoWhitespace Digit NoWhitespace [MinutesOffset]

MinutesOffset
    ":" NoWhitespace Digit NoWhitespace Digit

DurationLiteral
    "Duration:P" [YearsDuration] [MonthsDuration] [DaysDuration] [TimeDuration]

TimeDuration
     "T" NoWhitespace [HoursDuration] NoWhitespace [MinutesDuration] NoWhitespace [SecondsDuration]

YearsDuration
    DigitsNoUnderscores NoWhitespace "Y"

MonthsDuration
    DigitsNoUnderscores NoWhitespace "M"

DaysDuration
    DigitsNoUnderscores NoWhitespace "D"

HoursDuration
    DigitsNoUnderscores NoWhitespace "H"

MinutesDuration
    DigitsNoUnderscores NoWhitespace "M"

SecondsDuration
    DigitsNoUnderscores NoWhitespace "S"

PathLiteral
    "Path:" NoWhitespace Dir NoWhitespace [PathName]

FileLiteral
    ["File:"] NoWhitespace File

DirectoryLiteral
    ["Directory:"] NoWhitespace Dir

FileStoreLiteral
    "FileStore:" NoWhitespace Dir NoWhitespace [PathName]

File
    Dir NoWhitespace PathName

Dir
    "/" NoWhitespace [DirElements]
    "./" NoWhitespace [DirElements]
    "../" NoWhitespace [DirElements]

DirElements
    DirElement
    DirElements NoWhitespace DirElement

DirElement
    "../"
    PathName NoWhitespace "/"

PathName
    ["."] NoWhitespace PathNameParts

PathNameParts
    PathNamePart
    PathNameParts NoWhitespace PathNameSpecial NoWhitespace PathNamePart

PathNamePart
    IdentifierTrails

PathNameSpecial
    "."
    "-"

IdentifierTrails
    IdentifierTrail
    IdentifierTrails IdentifierTrail

IdentifierTrail

TypeExpression
    IntersectingTypeExpression

ExtendedTypeExpression
    ExtendedIntersectingTypeExpression

AnyTypeExpression
    ExtendedTypeExpression

IntersectingTypeExpression
    UnionedTypeExpression
    IntersectingTypeExpression "+" UnionedTypeExpression
    IntersectingTypeExpression "-" UnionedTypeExpression

ExtendedIntersectingTypeExpression
    ExtendedUnionedTypeExpression
    ExtendedIntersectingTypeExpression "+" ExtendedUnionedTypeExpression
    ExtendedIntersectingTypeExpression "-" ExtendedUnionedTypeExpression

UnionedTypeExpression
    PrefixTypeExpression
    UnionedTypeExpression "|" PrefixTypeExpression

ExtendedUnionedTypeExpression
    ExtendedPrefixTypeExpression
    ExtendedUnionedTypeExpression "|" ExtendedPrefixTypeExpression

PrefixTypeExpression
    ["immutable"] [Annotations] PostfixTypeExpression

ExtendedPrefixTypeExpression
    ["immutable"] [TypeAccessModifier] [Annotations] ExtendedPostfixTypeExpression

TypeAccessModifier
    "struct"
    AccessModifier

PostfixTypeExpression
    PrimaryTypeExpression
    PostfixTypeExpression NoWhitespace "?"
    PostfixTypeExpression ArrayDims
    PostfixTypeExpression ArrayIndexes

ExtendedPostfixTypeExpression
    ExtendedPrimaryTypeExpression
    ExtendedPostfixTypeExpression NoWhitespace "?"
    ExtendedPostfixTypeExpression ArrayDims
    ExtendedPostfixTypeExpression ArrayIndexes

PrimaryTypeExpression
    "(" ExtendedTypeExpression ")"
    NamedTypeExpression
    FunctionTypeExpression

ExtendedPrimaryTypeExpression
    "(" ExtendedTypeExpression ")"
    NamedTypeExpression
    FunctionTypeExpression
    AnonTypeExpression
    "const"
    "enum"
    "module"
    "package"
    "service"
    "class"

NamedTypeExpression
    NamedTypeExpressionPart
    NamedTypeExpression "." [Annotations] NamedTypeExpressionPart

NamedTypeExpressionPart
    QualifiedName [NoAutoNarrowModifier] [TypeParameterTypeList] [TypeValueSet]

NoAutoNarrowModifier
    NoWhitespace "!"

TypeValueSet
    "{" TypeValueList "}"

TypeValueList
    TypeValue
    TypeValueList "," TypeValue

TypeValue
    Expression

AnonTypeExpression
    "{" NameOrSignatureList ";" "}"

NameOrSignatureList
    NameOrSignature
    NameOrSignatureList ";" NameOrSignature

NameOrSignature
    Name
    [PropertyModifiers] TypeExpression Name
    [MethodModifiers] [TypeParameterList] MethodIdentity ParameterList

FunctionTypeExpression
    "function" ["conditional"] ReturnList [Name] "(" [TypeExpressionList] ")"

NumericLiteral
    IntegerLiteral
    FloatingPointLiteral

IntegerLiteral
    [Sign] UnsignedIntegerLiteral

Sign
    "+"
    "-"

UnsignedIntegerLiteral
    BitLiteral
    OctalLiteral
    DigitLiteral
    HexitLiteral

Indicator
    BinaryIndicator
    HexIndicator
    OctalIndicator

BitLiteral
    "0" BinaryIndicator Bits

BinaryIndicator
    "B"
    "b"

Bits
    Bit [BitsOrUnderscores]

Bit
    "0"
    "1"

BitsOrUnderscores
    BitOrUnderscore
    BitsOrUnderscores BitOrUnderscore

BitOrUnderscore
    Bit
    "_"

OctalLiteral
    "0" OctalIndicator Octals

OctalIndicator
    "O"
    "o"

Octals
    Octal [OctalsOrUnderscores]

Octal
    "0".."7"

OctalsOrUnderscores
    OctalOrUnderscore
    OctalsOrUnderscores OctalOrUnderscore

OctalOrUnderscore
    Octal
    "_"

DigitLiteral
    Digits

Digits
    Digit [DigitsOrUnderscores]

Digit
    "0".."9"

DigitsOrUnderscores
    DigitOrUnderscore
    DigitsOrUnderscores DigitOrUnderscore

DigitOrUnderscore
    Digit
    "_"

HexitLiteral
    "0" HexIndicator Hexits

HexIndicator
    "X"
    "x"

Hexits
    Hexit [HexitsOrUnderscores]

Hexit
    "0".."9"
    "A".."F"
    "a".."f"

HexitsOrUnderscores
    HexitOrUnderscore
    HexitsOrUnderscores HexitOrUnderscore

HexitOrUnderscore
    Hexit
    "_"

FloatingPointLiteral
    IntegerLiteral Exponent
    [Sign] FractionalLiteral [Exponent]

FractionalLiteral
    "0" BinaryIndicator [Bits] "." Bits
    "0" "o" [Octals] "." Octals
    [Digits] "." Digits
    "0" HexIndicator [Hexits] "." Hexits

Exponent
    ExponentIndicator IntegerLiteral

ExponentIndicator
    DecimalExponentIndicator
    BinaryExponentIndicator

DecimalExponentIndicator
    "E"
    "e"

BinaryExponentIndicator
    "P"
    "p"
