[versions]
#xdk = "unspecified"

lsp4j = "0.23.1"
slf4j = "2.0.13"

[plugins]
#xtc = { id = "org.xtclang.xtc-plugin", version.ref = "xtc-plugin" }

[libraries]
lsp4j = { group = "org.eclipse.lsp4j", name = "org.eclipse.lsp4j", version.ref = "lsp4j" }
lsp4j-jsonrpc = { group = "org.eclipse.lsp4j", name = "org.eclipse.lsp4j.jsonrpc", version.ref = "lsp4j" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }

#[bundles]
#unicode = ["javax-activation", "jakarta-xml-bind-api", "jaxb-runtime"]
