/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation(libs.lsp4j)
    implementation(libs.slf4j.api)
    implementation(libs.slf4j.simple)
    testImplementation(libs.slf4j.api)
    testImplementation(libs.slf4j.simple)
}

application {
    // Define the main class for the application.
    mainClass = "org.xtclang.lsp.server.XtcLanguageServer"
}
