/*
 * This source file was generated by the Gradle 'init' task
 */
package org.xtclang.utilities;

import org.xtclang.lsp.client.XtcLanguageClient;

class JoinUtils {
    public static String join(XtcLanguageClient source) {
        StringBuilder result = new StringBuilder();
        for (int i = 0; i < source.size(); ++i) {
            if (result.length() > 0) {
                result.append(" ");
            }
            result.append(source.get(i));
        }

        return result.toString();
    }
}
