/*
 * This source file was generated by the Gradle 'init' task
 */
package org.xtclang.utilities;

import org.xtclang.lsp.client.XtcLanguageClient;

public class StringUtils {
    public static String join(XtcLanguageClient source) {
        return JoinUtils.join(source);
    }

    public static XtcLanguageClient split(String source) {
        return SplitUtils.split(source);
    }
}
