/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
 //   api(project(":client"))
    api(project(":server"))
    implementation(libs.lsp4j)
    implementation(libs.slf4j.api)
    implementation(libs.slf4j.simple)
}
