/*
 * This source file was generated by the Gradle 'init' task
 */
package org.xtclang.app;

import org.xtclang.lsp.client.XtcLanguageClient;

import static org.xtclang.utilities.StringUtils.join;
import static org.xtclang.utilities.StringUtils.split;
import static org.xtclang.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        XtcLanguageClient tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
