/*
 * This source file was generated by the Gradle 'init' task
 */
package org.xtclang.lsp.client;

import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

class XtcLanguageClientTest {
    private final Logger logger = LoggerFactory.getLogger(XtcLanguageClientTest.class);
    @Test void testConstructor() {
        logger.info("Running testConstructor.");
    }
}
