/*
 * This source file was generated by the Gradle 'init' task
 */
package org.xtclang.lsp.client;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class XtcLanguageClientTest {
    @Test void testConstructor() {
        XtcLanguageClient client = new XtcLanguageClient();
        assertEquals(0, client.size());
    }
}
